#!/usr/bin/env node
// Generates .vale.ini and styles/XeroIP/*.yml from docs/prose/rules.yml.
//
// The point of generating rather than hand-writing: the prose standard is the
// research output in master-language-rule.md, rules.yml is its machine-readable
// subset, and the Vale config is downstream of both. Hand-maintaining the Vale
// styles would put a third copy of every marker in the repo, and the three would
// diverge the first time a rule changed.
//
// Tier -> Vale severity:  ban -> error, limit -> warning, monitor -> suggestion.

const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");

const ROOT = path.resolve(__dirname, "..");
const RULES = path.join(ROOT, "docs", "prose", "rules.yml");
const STYLE_DIR = path.join(ROOT, "styles", "XeroIP");

// js-yaml, not a hand-rolled reader.
//
// This function was 80 lines of line-oriented regex parsing, written to keep the
// repo free of npm dependencies. That goal was not worth its cost: the repo
// already requires Node, Python, Vale and gitleaks in CI, so "no dependencies"
// only ever meant "no package.json", and the parser failed toward permissiveness
// in two ways that both passed CI silently.
//
//   max_per: 500  # per prose window   ->  the string "500  # per prose window"
//   an entry indented two spaces too far -> dropped, no error, exit 0
//
// The second is the dangerous one: a rule vanishes, the generator succeeds, and
// the gate stops catching what it was written to catch. Load the file with a
// real parser and both classes of bug disappear.
function parseRules(text) {
  const doc = yaml.load(text, { filename: RULES });

  if (!doc || typeof doc !== "object") {
    throw new Error(`${RULES}: expected a mapping at the top level`);
  }

  const out = {};
  for (const tier of ["ban", "limit", "monitor"]) {
    const entries = doc[tier];
    if (entries === undefined) {
      throw new Error(`${RULES}: missing required tier '${tier}'`);
    }
    if (!Array.isArray(entries)) {
      throw new Error(`${RULES}: tier '${tier}' must be a list, got ${typeof entries}`);
    }
    out[tier] = entries;
  }

  // Anything outside the three tiers is either a typo'd tier name or a key that
  // was meant to do something. Both are worth failing on rather than ignoring.
  const KNOWN_TOP = new Set(["version", "source", "source_version", "ban", "limit", "monitor"]);
  for (const key of Object.keys(doc)) {
    if (!KNOWN_TOP.has(key)) {
      throw new Error(`${RULES}: unknown top-level key '${key}'`);
    }
  }

  return out;
}

const SEVERITY = { ban: "error", limit: "warning", monitor: "suggestion" };

// Vale matches raw tokens; escape anything regex-significant in a literal term.
const escape = (t) => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

// Every token is emitted as a YAML single-quoted scalar, where an apostrophe has
// to be doubled. Without this, any term containing one ("It's worth noting that")
// produces a styles file Vale cannot parse.
const yq = (s) => `'${String(s).replace(/'/g, "''")}'`;

function ruleFile(tier, entry) {
  const level = SEVERITY[tier];
  const lines = [];
  lines.push(`# GENERATED by tools/build-vale.js from docs/prose/rules.yml.`);
  lines.push(`# Do not edit. Marker ${entry.id} — see docs/prose/master-language-rule.md.`);
  lines.push(`extends: existence`);
  lines.push(`message: "${entry.id} (${entry.name}): '%s'."`);
  lines.push(`level: ${level}`);
  lines.push(`ignorecase: true`);

  if (entry.max_occurrences || entry.max_per_document) {
    // `occurrence` counts matches per scope instead of flagging each one, which is
    // what a frequency cap means. Vale has no per-500-words window, so a document
    // cap is the closest honest approximation; the prose cap stays in the checklist.
    lines.length = 0;
    lines.push(`# GENERATED by tools/build-vale.js from docs/prose/rules.yml.`);
    lines.push(`# Do not edit. Marker ${entry.id} — see docs/prose/master-language-rule.md.`);
    lines.push(`#`);
    lines.push(`# Frequency cap, not a ban. rules.yml sets ${entry.max_per_document
      ? `${entry.max_per_document} per document`
      : `${entry.max_occurrences} per ${entry.max_per} words`}; Vale counts per file.`);
    lines.push(`extends: occurrence`);
    lines.push(`message: "${entry.id} (${entry.name}): over the cap of ${
      entry.max_per_document || entry.max_occurrences}."`);
    lines.push(`level: ${level}`);
    lines.push(`max: ${entry.max_per_document || entry.max_occurrences}`);
    lines.push(`scope: text`);
    lines.push(`ignorecase: true`);
    lines.push(`token: ${yq(entry.pattern || `(?:${(entry.terms || []).map(escape).join("|")})`)}`);
    return lines.join("\n") + "\n";
  }

  if (entry.swap && entry.swap.length) {
    lines.push(`#`);
    lines.push(`# Preferred alternatives: ${entry.swap.join(", ")}.`);
  }
  if (entry.allowed) {
    lines.push(`# Allowed contexts: ${entry.allowed}`);
  }
  lines.push(`tokens:`);
  if (entry.pattern) {
    lines.push(`  - ${yq(entry.pattern)}`);
  } else {
    for (const t of entry.terms || []) lines.push(`  - ${yq(escape(t))}`);
  }
  return lines.join("\n") + "\n";
}

const rules = parseRules(fs.readFileSync(RULES, "utf8"));

fs.rmSync(STYLE_DIR, { recursive: true, force: true });
fs.mkdirSync(STYLE_DIR, { recursive: true });

let count = 0;
for (const tier of ["ban", "limit", "monitor"]) {
  for (const entry of rules[tier]) {
    if (!entry.id || !entry.name) throw new Error(`entry missing id or name in ${tier}`);
    if (!entry.pattern && !(entry.terms || []).length) {
      throw new Error(`${entry.id} has neither terms nor pattern`);
    }
    fs.writeFileSync(path.join(STYLE_DIR, `${entry.id}.yml`), ruleFile(tier, entry));
    count++;
  }
}

const ini = `# GENERATED by tools/build-vale.js from docs/prose/rules.yml. Do not edit.
StylesPath = styles
MinAlertLevel = warning

[*.md]
BasedOnStyles = XeroIP

# The imported research and its vendor variants quote every banned marker as an
# example, so linting them would report the standard against itself.
[docs/prose/**]
BasedOnStyles =

# Generated agent files mirror AGENTS.md; lint the source, not the copies.
[{CLAUDE.md,.github/copilot-instructions.md}]
BasedOnStyles =
`;
fs.writeFileSync(path.join(ROOT, ".vale.ini"), ini);

console.log(`${count} rules generated into styles/XeroIP/ (${rules.ban.length} error, ` +
  `${rules.limit.length} warning, ${rules.monitor.length} suggestion), plus .vale.ini`);
