#!/usr/bin/env node
// Generates .vale.ini and styles/XeroIP/*.yml from docs/prose/rules.yml.
//
// The point of generating rather than hand-writing: the prose standard is the
// research output in master-language-rule.md, rules.yml is its machine-readable
// subset, and the Vale config is downstream of both. Hand-maintaining the Vale
// styles would put a third copy of every marker in the repo, and the three would
// diverge the first time a rule changed.
//
// Tier -> Vale severity:  ban -> error, limit -> warning, monitor -> suggestion.

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const RULES = path.join(ROOT, "docs", "prose", "rules.yml");
const STYLE_DIR = path.join(ROOT, "styles", "XeroIP");

// Minimal YAML reader for the shape rules.yml actually uses: two-space nesting,
// scalars, inline [a, b] lists, block lists, and >- folded scalars. Avoids a
// dependency for a file this repo fully controls, and fails loudly on anything
// outside that shape rather than guessing.
function parseRules(text) {
  const out = { ban: [], limit: [], monitor: [] };
  const lines = text.split("\n");
  let tier = null;
  let entry = null;
  let folding = null;

  const parseInline = (v) => {
    if (!v.startsWith("[")) return null;
    const inner = v.slice(1, v.lastIndexOf("]"));
    if (!inner.trim()) return [];
    return inner
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean)
      .map(unquote);
  };
  const unquote = (s) => s.replace(/^['"]|['"]$/g, "");

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    if (/^\s*#/.test(raw) || !raw.trim()) {
      if (folding && !raw.trim()) continue;
      if (!folding) continue;
    }

    // Continuation of a folded scalar: deeper indent than the key that opened it.
    if (folding) {
      const indent = raw.match(/^\s*/)[0].length;
      if (raw.trim() && indent > folding.indent) {
        folding.parts.push(raw.trim());
        continue;
      }
      entry[folding.key] = folding.parts.join(" ");
      folding = null;
    }

    const tierMatch = /^(ban|limit|monitor):\s*$/.exec(raw);
    if (tierMatch) {
      if (entry && tier) out[tier].push(entry);
      entry = null;
      tier = tierMatch[1];
      continue;
    }
    if (!tier) continue;

    const itemMatch = /^\s{2}-\s+(\w+):\s*(.*)$/.exec(raw);
    if (itemMatch) {
      if (entry) out[tier].push(entry);
      entry = {};
      const [, key, value] = itemMatch;
      entry[key] = unquote(value.trim());
      continue;
    }

    const kvMatch = /^\s{4}([\w_]+):\s*(.*)$/.exec(raw);
    if (kvMatch && entry) {
      const [, key, valueRaw] = kvMatch;
      const value = valueRaw.trim();
      if (value === ">-" || value === ">") {
        folding = { key, indent: raw.match(/^\s*/)[0].length, parts: [] };
        continue;
      }
      const inline = parseInline(value);
      if (inline) { entry[key] = inline; continue; }
      if (value === "") {
        // Block list on following lines.
        const items = [];
        while (/^\s{6}-\s+/.test(lines[i + 1] || "")) {
          items.push(unquote(lines[++i].replace(/^\s{6}-\s+/, "").trim()));
        }
        entry[key] = items;
        continue;
      }
      entry[key] = /^\d+$/.test(value) ? Number(value) : unquote(value);
    }
  }
  if (folding) entry[folding.key] = folding.parts.join(" ");
  if (entry && tier) out[tier].push(entry);
  return out;
}

const SEVERITY = { ban: "error", limit: "warning", monitor: "suggestion" };

// Vale matches raw tokens; escape anything regex-significant in a literal term.
const escape = (t) => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

// Every token is emitted as a YAML single-quoted scalar, where an apostrophe has
// to be doubled. Without this, any term containing one ("It's worth noting that")
// produces a styles file Vale cannot parse.
const yq = (s) => `'${String(s).replace(/'/g, "''")}'`;

function ruleFile(tier, entry) {
  const level = SEVERITY[tier];
  const lines = [];
  lines.push(`# GENERATED by tools/build-vale.js from docs/prose/rules.yml.`);
  lines.push(`# Do not edit. Marker ${entry.id} — see docs/prose/master-language-rule.md.`);
  lines.push(`extends: existence`);
  lines.push(`message: "${entry.id} (${entry.name}): '%s'."`);
  lines.push(`level: ${level}`);
  lines.push(`ignorecase: true`);

  if (entry.max_occurrences || entry.max_per_document) {
    // `occurrence` counts matches per scope instead of flagging each one, which is
    // what a frequency cap means. Vale has no per-500-words window, so a document
    // cap is the closest honest approximation; the prose cap stays in the checklist.
    lines.length = 0;
    lines.push(`# GENERATED by tools/build-vale.js from docs/prose/rules.yml.`);
    lines.push(`# Do not edit. Marker ${entry.id} — see docs/prose/master-language-rule.md.`);
    lines.push(`#`);
    lines.push(`# Frequency cap, not a ban. rules.yml sets ${entry.max_per_document
      ? `${entry.max_per_document} per document`
      : `${entry.max_occurrences} per ${entry.max_per} words`}; Vale counts per file.`);
    lines.push(`extends: occurrence`);
    lines.push(`message: "${entry.id} (${entry.name}): over the cap of ${
      entry.max_per_document || entry.max_occurrences}."`);
    lines.push(`level: ${level}`);
    lines.push(`max: ${entry.max_per_document || entry.max_occurrences}`);
    lines.push(`scope: text`);
    lines.push(`ignorecase: true`);
    lines.push(`token: ${yq(entry.pattern || `(?:${(entry.terms || []).map(escape).join("|")})`)}`);
    return lines.join("\n") + "\n";
  }

  if (entry.swap && entry.swap.length) {
    lines.push(`#`);
    lines.push(`# Preferred alternatives: ${entry.swap.join(", ")}.`);
  }
  if (entry.allowed) {
    lines.push(`# Allowed contexts: ${entry.allowed}`);
  }
  lines.push(`tokens:`);
  if (entry.pattern) {
    lines.push(`  - ${yq(entry.pattern)}`);
  } else {
    for (const t of entry.terms || []) lines.push(`  - ${yq(escape(t))}`);
  }
  return lines.join("\n") + "\n";
}

const rules = parseRules(fs.readFileSync(RULES, "utf8"));

fs.rmSync(STYLE_DIR, { recursive: true, force: true });
fs.mkdirSync(STYLE_DIR, { recursive: true });

let count = 0;
for (const tier of ["ban", "limit", "monitor"]) {
  for (const entry of rules[tier]) {
    if (!entry.id || !entry.name) throw new Error(`entry missing id or name in ${tier}`);
    if (!entry.pattern && !(entry.terms || []).length) {
      throw new Error(`${entry.id} has neither terms nor pattern`);
    }
    fs.writeFileSync(path.join(STYLE_DIR, `${entry.id}.yml`), ruleFile(tier, entry));
    count++;
  }
}

const ini = `# GENERATED by tools/build-vale.js from docs/prose/rules.yml. Do not edit.
StylesPath = styles
MinAlertLevel = warning

[*.md]
BasedOnStyles = XeroIP

# The imported research and its vendor variants quote every banned marker as an
# example, so linting them would report the standard against itself.
[docs/prose/**]
BasedOnStyles =

# Generated agent files mirror AGENTS.md; lint the source, not the copies.
[{CLAUDE.md,.github/copilot-instructions.md}]
BasedOnStyles =
`;
fs.writeFileSync(path.join(ROOT, ".vale.ini"), ini);

console.log(`${count} rules generated into styles/XeroIP/ (${rules.ban.length} error, ` +
  `${rules.limit.length} warning, ${rules.monitor.length} suggestion), plus .vale.ini`);
