#!/usr/bin/env python3
"""Vendor the standards into a consuming repository.

Generalises the base-plus-tail model already working in XeroIP/copilot-memory,
where a shared base file and a per-host tail are assembled into a derived file
that is never edited directly. This does the same, with repos in place of hosts.

What it writes into the target repo:

    .standards/            a copy of docs/, plus VERSION and the prose rules
    AGENTS.md              assembled from the shared base + the repo's own tail
    CLAUDE.md              generated from AGENTS.md
    .github/copilot-instructions.md   generated from AGENTS.md

The repo keeps its own voice in .standards-tail.md. That file is the repo's and
is never overwritten; everything else under .standards/ is derived and is
replaced wholesale on each sync.

Vendoring rather than submoduling is deliberate: it puts the rules in the working
tree an agent already has, with no network fetch and no submodule to go stale.

Usage:
    python3 tools/sync-standards.py --target ../my-unraid-notes
    python3 tools/sync-standards.py --target ../my-unraid-notes --check
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

BANNER = (
    "<!-- GENERATED by tools/sync-standards.py in XeroIP/standards.\n"
    "     The shared section below is replaced on every sync. Repo-specific\n"
    "     instructions belong in .standards-tail.md, which is never overwritten. -->"
)

TAIL_FILE = ".standards-tail.md"
VENDOR_DIR = ".standards"


def standards_version() -> str:
    """Describe the standards commit being vendored, so a target can say what it has."""
    try:
        return subprocess.run(
            ["git", "-C", str(ROOT), "describe", "--tags", "--always", "--dirty"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def load_profile(target: Path) -> dict:
    """Read the target's .standards.yml.

    Deliberately shallow: only the keys that change what gets written are read,
    with a scalar parser rather than a YAML dependency. An unreadable or missing
    file is not fatal — it means the repo has not declared a profile yet, and the
    sync should still deliver the text.
    """
    profile = {"profile": "mixed", "stacks": []}
    path = target / ".standards.yml"
    if not path.exists():
        return profile
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].rstrip()
        if line.startswith("profile:"):
            profile["profile"] = line.split(":", 1)[1].strip().strip("\"'")
        elif line.startswith("stacks:"):
            value = line.split(":", 1)[1].strip()
            if value.startswith("["):
                inner = value[1 : value.rfind("]")]
                profile["stacks"] = [s.strip().strip("\"'") for s in inner.split(",") if s.strip()]
    return profile


def build_agents_md(target: Path, profile: dict) -> str:
    """Shared base, then the repo's own tail if it has one."""
    base = (ROOT / "docs" / "coding" / "global.md").read_text(encoding="utf-8")
    # Strip front matter; the assembled file is not a docs page.
    if base.startswith("---"):
        base = base.split("---", 2)[2].lstrip("\n")

    stacks = ", ".join(profile["stacks"]) if profile["stacks"] else "none declared"
    parts = [
        "# Repository instructions",
        "",
        BANNER,
        "",
        f"Standards version: `{standards_version()}`  ",
        f"Profile: `{profile['profile']}`  ",
        f"Stacks: {stacks}",
        "",
        "The full standards are vendored in `.standards/`. The rules that apply to every",
        "repository follow; anything specific to this one is at the end of the file.",
        "",
        "---",
        "",
        base.rstrip(),
        "",
    ]

    tail_path = target / TAIL_FILE
    if tail_path.exists():
        parts += ["---", "", "## This repository", "", tail_path.read_text(encoding="utf-8").strip(), ""]

    return "\n".join(parts)


def vendor_docs(target: Path, dry_run: bool) -> list[str]:
    """Replace .standards/ wholesale. It is derived; nothing in it is edited in place."""
    dest = target / VENDOR_DIR
    changed = []

    if dry_run:
        src_docs = ROOT / "docs"
        for src in sorted(src_docs.rglob("*")):
            if src.is_dir():
                continue
            rel = src.relative_to(src_docs)
            mirror = dest / "docs" / rel
            if not mirror.exists() or not filecmp.cmp(src, mirror, shallow=False):
                changed.append(str(Path(VENDOR_DIR) / "docs" / rel))
        return changed

    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(ROOT / "docs", dest / "docs")
    (dest / "VERSION").write_text(standards_version() + "\n", encoding="utf-8")
    (dest / "README.md").write_text(
        "# Vendored standards\n\n"
        "Copied from XeroIP/standards by its sync workflow. Every file here is derived:\n"
        "edits are lost on the next sync. Change the standard upstream instead.\n\n"
        f"Version: `{standards_version()}`\n",
        encoding="utf-8",
    )
    return [str(Path(VENDOR_DIR))]


def write_agent_files(target: Path, agents_md: str, dry_run: bool) -> list[str]:
    """AGENTS.md is the source; the vendor files are copies of it with a header."""
    outputs = {
        target / "AGENTS.md": agents_md,
        target / "CLAUDE.md": agents_md,
        target / ".github" / "copilot-instructions.md": agents_md,
    }
    changed = []
    for path, content in outputs.items():
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing == content:
            continue
        changed.append(str(path.relative_to(target)))
        if dry_run:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", required=True, type=Path, help="path to the consuming repo")
    parser.add_argument("--check", action="store_true",
                        help="report what would change and exit 1 if anything would")
    args = parser.parse_args()

    target = args.target.resolve()
    if not (target / ".git").exists():
        print(f"error: {target} is not a git repository", file=sys.stderr)
        return 2

    profile = load_profile(target)
    agents_md = build_agents_md(target, profile)

    changed = vendor_docs(target, args.check) + write_agent_files(target, agents_md, args.check)

    if args.check:
        if changed:
            print(f"{len(changed)} path(s) out of date in {target.name}:")
            for c in changed[:20]:
                print(f"  {c}")
            if len(changed) > 20:
                print(f"  ... and {len(changed) - 20} more")
            return 1
        print(f"{target.name} is up to date with standards {standards_version()}")
        return 0

    print(f"synced {target.name} to standards {standards_version()} "
          f"(profile: {profile['profile']})")
    for c in changed:
        print(f"  {c}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
