#!/usr/bin/env python3
"""Vendor the standards into a consuming repository.

Generalises the base-plus-tail model already working in XeroIP/copilot-memory,
where a shared base file and a per-host tail are assembled into a derived file
that is never edited directly. This does the same, with repos in place of hosts.

What it writes into the target repo:

    .standards/            a copy of docs/, plus VERSION and the prose rules
    AGENTS.md              assembled from the shared base + the repo's own tail
    CLAUDE.md              generated from AGENTS.md
    .github/copilot-instructions.md   generated from AGENTS.md

The repo keeps its own voice in .standards-tail.md. That file is the repo's and
is never overwritten; everything else under .standards/ is derived and is
replaced wholesale on each sync, except paths the repo lists in `sync.protect`,
which are kept as they are and reported on every run.

Each generated agent file carries a content hash. A later sync refuses when the
file no longer matches it, because the difference is someone's edit and a sync
would delete it. A region the repo declares in `sync.managed_regions` is left
out of the hash, so a tool that maintains it doesn't trip the check; the
regenerated file doesn't carry the region over (#36).

The sync also writes `standards_version` in the repo's .standards.yml to the
version it vendored, so the pin records what the repo holds.

Vendoring rather than submoduling is deliberate: it puts the rules in the working
tree an agent already has, with no network fetch and no submodule to go stale.

Usage:
    python3 tools/sync-standards.py --target ../my-unraid-notes
    python3 tools/sync-standards.py --target ../my-unraid-notes --check
"""

from __future__ import annotations

import argparse
import filecmp
import hashlib
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

BANNER = (
    "<!-- GENERATED by tools/sync-standards.py in XeroIP/standards.\n"
    "     The shared section below is replaced on every sync. Repo-specific\n"
    "     instructions belong in .standards-tail.md, which is never overwritten. -->"
)

TAIL_FILE = ".standards-tail.md"
VENDOR_DIR = ".standards"
AGENT_FILES = ("AGENTS.md", "CLAUDE.md", ".github/copilot-instructions.md")

# The generated files' content hash, on its own line under the banner. It's
# computed with this line removed, so writing it doesn't change it.
HASH_RE = re.compile(r"^<!-- sync-hash: sha256:([0-9a-f]{64}) -->\n", re.M)
NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")

# What gets vendored. The rules and the tools that enforce them travel together,
# deliberately.
#
# Vendoring `docs/` alone left a repo's rules pinned by its own commit while the
# gate enforcing them was fetched live from a mutable tag. Any gap between a tag
# moving and thirty sync PRs merging was a window where CI enforced one version
# and `.standards/docs/` — the copy a person or an agent reads — described
# another. Shipping both from the same commit removes the gap by construction.
#
# (dir_or_file, destination name) relative to the repo root.
VENDORED = [
    ("docs", "docs"),
    ("tools", "tools"),
    ("styles", "styles"),
    (".vale.ini", ".vale.ini"),
    (".markdownlint-cli2.jsonc", ".markdownlint-cli2.jsonc"),
]

# secret-scan.yml falls back to .standards/.gitleaks.toml when a repo has none of
# its own; without one, a freshly synced repo failed gitleaks on a missing file.
# It is written, not copied: see vendored_gitleaks_config().
GITLEAKS_CONFIG = ".gitleaks.toml"

GITLEAKS_HEADER = (
    "# Written by tools/sync-standards.py in XeroIP/standards, from that\n"
    "# repository's .gitleaks.toml. Edits here are lost on the next sync.\n"
    "#\n"
    "# The same rules, without that repository's path exclusions. Its exclusion is\n"
    "# warranted by review there: one fixture directory holds a fake token on\n"
    "# purpose, and is reviewed on the same terms as the rest of that repository.\n"
    "# The warrant does not travel. Anchored at this repository's root, the same\n"
    "# pattern would exempt this repository's own tests/fixtures/leakage/, which\n"
    "# nobody reviewing the standards reads, so a real key there would go\n"
    "# unreported.\n"
    "#\n"
    "# To exclude a path here, write a .gitleaks.toml at this repository's root.\n"
    "# secret-scan.yml uses that file in preference to this one, so the exclusion is\n"
    "# explicit and this repository's own.\n"
    "\n"
)


def standards_version() -> str:
    """Describe the standards commit being vendored, so a target can say what it has."""
    try:
        return subprocess.run(
            ["git", "-C", str(ROOT), "describe", "--tags", "--always", "--dirty"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def load_profile(target: Path) -> dict:
    """Read the target's .standards.yml.

    Deliberately shallow: only the keys that change what gets written are read,
    with a scalar parser rather than a YAML dependency. An unreadable or missing
    file is not fatal — it means the repo has not declared a profile yet, and the
    sync should still deliver the text.
    """
    profile = {"profile": "mixed", "stacks": [], "visibility": "public",
               "adopted": False, "standards_version": "",
               "protect": [], "managed_regions": []}
    path = target / ".standards.yml"
    if not path.exists():
        return profile
    in_sync = False
    list_key = None
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        # sync.protect and sync.managed_regions, as a flow list or a block list.
        if not line.startswith((" ", "\t")):
            in_sync, list_key = line.startswith("sync:"), None
        elif in_sync:
            key = re.match(r"\s*(protect|managed_regions):\s*(.*)$", line)
            item = re.match(r"\s*-\s+(.*)$", line)
            if key:
                name, value = key.groups()
                list_key = name if not value else None
                if value.startswith("["):
                    inner = value[1 : value.rfind("]")]
                    profile[name] = [v.strip().strip("\"'") for v in inner.split(",") if v.strip()]
                continue
            if item and list_key:
                profile[list_key].append(item.group(1).strip().strip("\"'"))
                continue
            list_key = None
        if line.startswith("profile:"):
            profile["profile"] = line.split(":", 1)[1].strip().strip("\"'")
        elif line.strip().startswith("adopted:"):
            profile["adopted"] = line.split(":", 1)[1].strip().strip("\"'").lower() == "true"
        elif line.startswith("standards_version:"):
            profile["standards_version"] = line.split(":", 1)[1].strip().strip("\"'")
        elif line.startswith("visibility:"):
            profile["visibility"] = line.split(":", 1)[1].strip().strip("\"'")
        elif line.startswith("stacks:"):
            value = line.split(":", 1)[1].strip()
            if value.startswith("["):
                inner = value[1 : value.rfind("]")]
                profile["stacks"] = [s.strip().strip("\"'") for s in inner.split(",") if s.strip()]
    return profile


def region_pattern(name: str) -> re.Pattern:
    """A declared region, from its start marker (any version: `v2`, `v3`) to its
    end marker, inclusive."""
    return re.compile(rf"^<!-- {re.escape(name)}:start[^\n]*-->\n.*?"
                      rf"^<!-- {re.escape(name)}:end -->[ \t]*\n?", re.M | re.S)


def content_hash(text: str, regions: list[str]) -> str:
    """sha256 of the text without its hash line and its declared regions.

    Runs of three or more newlines then collapse to two, so a region that stood
    between two paragraphs leaves the text it was removed from unchanged. Other
    blank lines still count: a region spliced into the middle of a paragraph,
    with blank lines around it, splits that paragraph, and the hash catches it.
    A region that isn't declared is hashed like any other text, and a declared
    one that isn't there leaves the whole file hashed, so both mistakes refuse
    rather than pass."""
    text = HASH_RE.sub("", text)
    for name in regions:
        text = region_pattern(name).sub("", text)
    text = re.sub(r"\n{3,}", "\n\n", text).rstrip() + "\n"
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def region_report(rel: str, text: str, regions: list[str]) -> list[str]:
    """Where each declared region is and how much of the file it covers. Printed
    on every run, so a declaration wide enough to hide an edit is visible."""
    total = len(text.splitlines()) or 1
    out = []
    for name in regions:
        spans = list(region_pattern(name).finditer(text))
        if not spans:
            out.append(f"{rel}: managed region '{name}' declared but not present; "
                       "whole-file hash applies")
        for m in spans:
            first = text.count("\n", 0, m.start()) + 1
            last = first + m.group(0).rstrip("\n").count("\n")
            n = last - first + 1
            out.append(f"{rel}: skipping managed region '{name}' at lines {first}-{last} "
                       f"({n} of {total} lines, {100 * n // total}%)")
    return out


def build_agents_md(target: Path, profile: dict) -> str:
    """Shared base, then the repo's own tail if it has one."""
    base = (ROOT / "docs" / "coding" / "global.md").read_text(encoding="utf-8")
    # Strip front matter; the assembled file is not a docs page.
    if base.startswith("---"):
        base = base.split("---", 2)[2].lstrip("\n")
    # The assembled file has its own H1. The base's second one failed MD025 in
    # every consumer's docs gate, on a file the consumer can't edit.
    base = re.sub(r"^# ", "## ", base, count=1, flags=re.M)

    stacks = ", ".join(profile["stacks"]) if profile["stacks"] else "none declared"
    parts = [
        "# Repository instructions",
        "",
        BANNER,
        "",
        f"Standards version: `{standards_version()}`  ",
        f"Profile: `{profile['profile']}`  ",
        f"Stacks: {stacks}",
        "",
        "The full standards are vendored in `.standards/`. The rules that apply to every",
        "repository follow; anything specific to this one is at the end of the file.",
        "",
        "---",
        "",
        base.rstrip(),
        "",
    ]

    tail_path = target / TAIL_FILE
    if tail_path.exists():
        parts += ["---", "", "## This repository", "", tail_path.read_text(encoding="utf-8").strip(), ""]

    text = "\n".join(parts)
    digest = content_hash(text, profile["managed_regions"])
    return text.replace(BANNER, f"{BANNER}\n<!-- sync-hash: sha256:{digest} -->", 1)


def vendored_gitleaks_config(source: str) -> str:
    """The standards repo's gitleaks config with its [allowlist] removed.

    Only a description and path exclusions may be dropped. A regex or stopword
    allowlist changes what the rules report, so whether it reaches every
    consumer is a decision, not a side effect: one is refused here rather than
    silently kept or silently lost. The result is parsed back and must equal the
    source minus its allowlist, so the text edit cannot take anything else."""
    config = tomllib.loads(source)
    if "allowlists" in config:
        raise SystemExit(f"sync: {GITLEAKS_CONFIG} uses [[allowlists]]; decide what a "
                         "consumer's copy keeps before vendoring it")
    allowlist = config.pop("allowlist", {})
    if set(allowlist) - {"description", "paths"}:
        raise SystemExit(f"sync: {GITLEAKS_CONFIG} [allowlist] holds more than path "
                         "exclusions; decide what a consumer's copy keeps before "
                         "vendoring it")

    # The [allowlist] table runs from its header to the next table or the end.
    out = re.sub(r"(?ms)^\[allowlist\][^\n]*\n.*?(?=^\[|\Z)", "", source)
    if tomllib.loads(out) != config:
        raise SystemExit(f"sync: removing [allowlist] from {GITLEAKS_CONFIG} "
                         "changed something else")
    return GITLEAKS_HEADER + out.rstrip("\n") + "\n"


def vendored_readme() -> str:
    return (
        "# Vendored standards\n\n"
        "Copied from XeroIP/standards by its sync workflow. Every file here is derived:\n"
        "edits are lost on the next sync. Change the standard upstream instead.\n\n"
        "`docs/` are the rules. `tools/`, `styles/`, `.vale.ini`, `.markdownlint-cli2.jsonc`\n"
        "and `.gitleaks.toml` are what enforces them, vendored from the same commit so\n"
        "the gate and the documentation cannot disagree about what the rules are. The CI\n"
        "workflow runs these copies rather than fetching the standards repo.\n\n"
        "`.gitleaks.toml` is written rather than copied: it carries the standards' rules\n"
        "without that repository's path exclusions. Its header says why.\n\n"
        "You can run the same checks locally:\n\n"
        "```bash\n"
        "python3 .standards/tools/check-docs.py docs\n"
        "vale --config=.standards/.vale.ini docs\n"
        "npx markdownlint-cli2 --config .standards/.markdownlint-cli2.jsonc\n"
        "```\n\n"
        f"Version: `{standards_version()}`\n"
    )


def vendored_files() -> dict[str, Path | str]:
    """Every file the sync writes under .standards/, by its path there: a source
    file to copy, or the text to write."""
    out: dict[str, Path | str] = {}
    for src_name, dest_name in VENDORED:
        src = ROOT / src_name
        if not src.exists():
            raise SystemExit(f"sync: {src_name} is missing from the standards repo")
        if src.is_file():
            out[dest_name] = src
            continue
        for f in sorted(src.rglob("*")):
            if f.is_file():
                out[str(Path(dest_name) / f.relative_to(src))] = f
    out[GITLEAKS_CONFIG] = vendored_gitleaks_config(
        (ROOT / GITLEAKS_CONFIG).read_text(encoding="utf-8"))
    out["VERSION"] = standards_version() + "\n"
    out["README.md"] = vendored_readme()
    return out


def protected(rel: str, protect: list[str]) -> bool:
    """Whether a path under .standards/ is one the repo asked the sync to keep."""
    return any(rel == p or rel.startswith(p.rstrip("/") + "/") for p in protect)


def vendor_docs(target: Path, protect: list[str], dry_run: bool) -> list[str]:
    """Replace .standards/ wholesale, except what sync.protect keeps.

    A protected path that exists is left exactly as it is; one that doesn't is
    written like any other, since there's nothing there to overwrite. In a
    check, a file the next sync would delete counts as a change, as an edited
    or missing one does: `up to date` has to mean the sync would do nothing."""
    dest = target / VENDOR_DIR
    files = vendored_files()
    kept = [p for p in protect if (dest / p).exists()]

    if dry_run:
        changed = []
        for rel, source in files.items():
            if protected(rel, kept):
                continue
            mirror = dest / rel
            if not mirror.is_file():
                changed.append(str(Path(VENDOR_DIR) / rel))
            elif isinstance(source, Path):
                if not filecmp.cmp(source, mirror, shallow=False):
                    changed.append(str(Path(VENDOR_DIR) / rel))
            elif mirror.read_text(encoding="utf-8") != source:
                changed.append(str(Path(VENDOR_DIR) / rel))
        if dest.exists():
            for f in sorted(dest.rglob("*")):
                rel = str(f.relative_to(dest))
                if f.is_file() and rel not in files and not protected(rel, kept):
                    changed.append(f"{VENDOR_DIR}/{rel} (not vendored: the next sync deletes it)")
        return changed

    with tempfile.TemporaryDirectory() as tmp:
        holding = Path(tmp)
        for p in kept:
            (holding / p).parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(dest / p), str(holding / p))

        if dest.exists():
            shutil.rmtree(dest)
        dest.mkdir(parents=True)
        for rel, source in files.items():
            out = dest / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            if isinstance(source, Path):
                shutil.copy2(source, out)
            else:
                out.write_text(source, encoding="utf-8")

        for p in kept:
            out = dest / p
            if out.is_dir():
                shutil.rmtree(out)
            elif out.exists():
                out.unlink()
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(holding / p), str(out))
    return [str(Path(VENDOR_DIR))]


def adoption_blockers(target: Path, profile: dict) -> list[str]:
    """Reasons this repo must not be written to yet.

    The presence of .standards.yml was previously treated as consent, and it is
    not: a repo can declare a profile long before anyone agrees to have three
    top-level files overwritten. The first sync into an established repository
    is destructive — AGENTS.md, CLAUDE.md and copilot-instructions.md are
    replaced wholesale, and a repo with a substantial hand-written CLAUDE.md
    loses it.

    Two independent gates, because either alone fails open:

      - `sync.adopted: true` is the owner's explicit statement of consent.
      - Any existing agent file must already carry the generated banner. A file
        without it was written by a person, and a declaration in a config file
        is not a reason to overwrite someone's prose.

    And a bannered file must still match its content hash, outside the regions
    the repo declares. The banner alone said who wrote the file first, not
    whether anyone added to it since: a section appended after a sync was
    deleted by the next one, with exit 0.
    """
    blockers = []
    regions = profile["managed_regions"]

    if not profile.get("adopted"):
        blockers.append(
            ".standards.yml does not set `sync.adopted: true`. The first sync "
            "overwrites AGENTS.md, CLAUDE.md and .github/copilot-instructions.md, "
            "so it needs the repo owner to opt in explicitly."
        )

    for rel in AGENT_FILES:
        path = target / rel
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        if BANNER.splitlines()[0] not in text:
            blockers.append(
                f"{rel} exists and was not generated by this tool (no banner). "
                f"Move anything worth keeping into {TAIL_FILE} first."
            )
            continue
        recorded = HASH_RE.search(text)
        if not recorded:
            blockers.append(
                f"{rel} carries the banner but no content hash, so an edit to it can't "
                "be told from generated text: it was written before the sync recorded "
                f"one. Move anything worth keeping into {TAIL_FILE}, then sync once "
                "with --adopt."
            )
        elif recorded.group(1) != content_hash(text, regions):
            blockers.append(
                f"{rel} was edited outside the regions declared in sync.managed_regions "
                f"since the last sync. Move the edit into {TAIL_FILE}, or declare its "
                "region if a tool maintains it."
            )

    return blockers


def pin_version(target: Path, version: str, dry_run: bool) -> list[str]:
    """Set standards_version in the repo's .standards.yml to what was vendored.

    Only that line changes, or is appended when missing; the rest of the file is
    the repo's and stays as written. A repo with no .standards.yml gets none."""
    path = target / ".standards.yml"
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    line = re.compile(r"^standards_version:[ \t]*([^#\n]*?)([ \t]*#[^\n]*)?$", re.M)
    found = line.search(text)
    if found and found.group(1).strip().strip("\"'") == version:
        return []
    if found:
        new = (text[: found.start()] + f"standards_version: {version}"
               + (found.group(2) or "") + text[found.end():])
    else:
        new = text + ("\n" if text and not text.endswith("\n") else "") + \
            f"standards_version: {version}\n"
    if not dry_run:
        path.write_text(new, encoding="utf-8")
    return [".standards.yml (standards_version)"]


def write_agent_files(target: Path, agents_md: str, dry_run: bool) -> list[str]:
    """AGENTS.md is the source; the vendor files are copies of it with a header."""
    outputs = {
        target / "AGENTS.md": agents_md,
        target / "CLAUDE.md": agents_md,
        target / ".github" / "copilot-instructions.md": agents_md,
    }
    changed = []
    for path, content in outputs.items():
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing == content:
            continue
        changed.append(str(path.relative_to(target)))
        if dry_run:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", required=True, type=Path, help="path to the consuming repo")
    parser.add_argument("--check", action="store_true",
                        help="report what would change and exit 1 if anything would")
    parser.add_argument("--adopt", action="store_true",
                        help="override the first-sync consent checks (see adoption_blockers)")
    args = parser.parse_args()

    target = args.target.resolve()
    if not (target / ".git").exists():
        print(f"error: {target} is not a git repository", file=sys.stderr)
        return 2

    profile = load_profile(target)

    # Both lists come from the repo's own file. A protect path names something
    # under .standards/, and a region name goes into a pattern.
    for p in profile["protect"]:
        parts = Path(p).parts
        if not parts or Path(p).is_absolute() or ".." in parts:
            print(f"error: sync.protect entry '{p}' must be a path inside {VENDOR_DIR}/",
                  file=sys.stderr)
            return 2
    for name in profile["managed_regions"]:
        if not NAME_RE.match(name):
            print(f"error: sync.managed_regions entry '{name}' must be lowercase letters, "
                  "digits and hyphens", file=sys.stderr)
            return 2

    for rel in AGENT_FILES:
        path = target / rel
        if path.exists():
            for line in region_report(rel, path.read_text(encoding="utf-8"),
                                      profile["managed_regions"]):
                print(line)
    for p in profile["protect"]:
        state = "kept as it is" if (target / VENDOR_DIR / p).exists() else \
            "not present, so vendored like any other path"
        print(f"{VENDOR_DIR}/{p}: sync.protect, {state}")

    blockers = adoption_blockers(target, profile)
    if blockers and not args.adopt:
        print(f"refusing to sync {target.name}:", file=sys.stderr)
        for b in blockers:
            print(f"  - {b}", file=sys.stderr)
        print("\nRun with --adopt to override, after reading what it would replace.",
              file=sys.stderr)
        return 3

    pinned = profile["standards_version"]
    if pinned and pinned != standards_version().split("-")[0]:
        print(f"warning: {target.name} pins standards {pinned}, but this tree is "
              f"{standards_version()}. Sync from the pinned tag instead.", file=sys.stderr)

    agents_md = build_agents_md(target, profile)

    changed = (vendor_docs(target, profile["protect"], args.check)
               + write_agent_files(target, agents_md, args.check)
               + pin_version(target, standards_version(), args.check))

    if args.check:
        if changed:
            print(f"{len(changed)} path(s) out of date in {target.name}:")
            for c in changed[:20]:
                print(f"  {c}")
            if len(changed) > 20:
                print(f"  ... and {len(changed) - 20} more")
            return 1
        print(f"{target.name} is up to date with standards {standards_version()}")
        return 0

    print(f"synced {target.name} to standards {standards_version()} "
          f"(profile: {profile['profile']})")
    for c in changed:
        print(f"  {c}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
